#cloud-config
package_update: true
packages:
  - autoconf
  - automake
  - autotools-dev
  - bash
  - bat
  - binutils
  - build-essential
  - ca-certificates
  - clang-22
  - clang-format-22
  - clang-tidy-22
  - curl
  - direnv
  - dnsutils
  - fd-find
  - fzf
  - g++
  - gcc
  - gdb
  - git
  - git-lfs
  - glibc-doc
  - gnupg
  - htop
  - inetutils-ping
  - iotop
  - iproute2
  - jq
  - less
  - libtool
  - linux-perf
  - lsof
  - ltrace
  - make
  - manpages-dev
  - nano
  - net-tools
  - nmap
  - nodejs
  - npm
  - python3
  - python3-pip
  - python3-venv
  - ripgrep
  - rsync
  - shfmt
  - socat
  - sqlite3
  - strace
  - sudo
  - tcpdump
  - traceroute
  - tree
  - unzip
  - unzip
  - valgrind
  - w3m
  - w3m-img
  - wget
  - xz-utils
  - zip
users:
  - name: agent
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
